# This file configures Travis CI to run builds on Linux and Mac machines for
# each pull request, to ensure the tests pass and to build Linux and Mac wheels
# of pyAT. If the build is triggered by a tag then the wheels are uploaded to
# TestPyPI using twine. For this repository TWINE_USERNAME and TWINE_PASSWORD
# are set in Travis CI under More options -> Settings -> Environment Variables.
language: python
matrix:
  include:
    - os: linux
      python: '2.7'
    - os: linux
      python: '3.4'
    - os: linux
      python: '3.5'
    - os: linux
      python: '3.6'
    - os: linux
      python: '3.7'

    - os: osx
      sudo: required
      language: generic
      env: PYTHON=2
    - os: osx
      sudo: required
      language: generic
      env: PYTHON=3

    - sudo: required
      services: docker
      env: CIBW_BEFORE_BUILD='pip install numpy'
    - os: osx
      language: generic
      env: CIBW_BEFORE_BUILD='pip install numpy'

install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    python$PYTHON -m pip install virtualenv
    python$PYTHON -m virtualenv venv
    source venv/bin/activate
    cd pyat
    pip$PYTHON install --only-binary=numpy,scipy -r requirements.txt
    python$PYTHON setup.py build
  else
    pip install virtualenv
    python -m virtualenv venv
    source venv/bin/activate
    cd pyat
    pip install --only-binary=numpy,scipy -r requirements.txt
    python setup.py build
  fi

before_script:
  - python setup.py develop

script: |
  if [[ $CIBW_BEFORE_BUILD != '' ]]; then
    rm -rf build
    python -m pip install --upgrade cibuildwheel
    cibuildwheel --output-dir wheelhouse
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
    fi
  else
    python -m pip install pytest-cov
    python -m pytest test --cov-report term-missing --cov=at
  fi
