# See the Python documentation: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# and cibuildwheel: https://cibuildwheel.readthedocs.io/en/stable/
name: Build and upload wheels and sdist

on:
  push:
    tags:
      - pyat-*

defaults:
  run:
    working-directory: pyat

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Prepare source
        run: |
          python -m pip install numpy==1.16.6
          python setup.py build

      - name: Remove built files
        if: (! contains(matrix.os, 'windows'))
        run: rm -rf build

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: pip install numpy==1.16.6
          CIBW_BUILD_VERBOSITY: 1

      - name: Build sdist
        run: python setup.py sdist

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./pyat/wheelhouse/*.whl
          if-no-files-found: error

      - name: Upload sdist
        uses: actions/upload-artifact@v2
        with:
          name: tar.gz
          path: ./pyat/dist/*.tar.gz
          if-no-files-found: error
