# This workflow will install Python dependencies, run tests and lint with a
# variety of Python version
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Python extension and Test GPU

on:
  workflow_dispatch:

jobs:
  build_and_run_tests:

    runs-on: ${{ matrix.os }}
#    container: intel/intel-gpu-initcontainer:devel
    timeout-minutes: 15

    strategy:
      matrix:
        python-version: ['3.12']
#        os: [macos-latest, ubuntu-latest]
        os: [macos-13]

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

#    - name: Install OpenCL
#      run: |
#        sudo apt-get install -y ocl-icd-opencl-dev
#        sudo apt-get install -y pocl-opencl-icd

#    - name: Install AMD drviers
#      run: |
#        sudo apt update
#        sudo apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
#        sudo usermod -a -G render,video $LOGNAME
#        wget https://repo.radeon.com/amdgpu-install/6.1.2/ubuntu/jammy/amdgpu-install_6.1.60102-1_all.deb
#        sudo apt install ./amdgpu-install_6.1.60102-1_all.deb
#        sudo apt update
#        sudo apt install amdgpu-dkms rocm

    - name: Build and install at with tests
      run: python -m pip install --config-settings opencl=1 -e ".[dev]"

    - name: Detect GPU
      working-directory: pyat
      run: python test/display_gpu.py

    - name: Test GPU
      working-directory: pyat
      run: python test/test_gpu.py
